---
# Source: rasa-x/templates/app-deployment.yaml
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: my-rasa-app
  labels:
    helm.sh/chart: rasa-x-5.0.0
    app.kubernetes.io/name: rasa-x
    app.kubernetes.io/instance: my-rasa
    app.kubernetes.io/version: "1.4.0"
    app.kubernetes.io/managed-by: Helm
    
    app.kubernetes.io/component: app
  annotations:
    sidecar.jaegertracing.io/inject: "false"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rasa-x
      app.kubernetes.io/instance: my-rasa
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rasa-x
        app.kubernetes.io/instance: my-rasa
        app.kubernetes.io/component: app
    spec:
      hostNetwork: false
      dnsPolicy: ClusterFirst
      automountServiceAccountToken: true
      
      
      securityContext:
        fsGroup: 1000
      containers:
      - name: rasa-x
        image: "rasa/rasa-x-demo:0.38.0"
        imagePullPolicy: Always
        ports:
        - name: "http"
          containerPort: 5055
          protocol: "TCP"
        livenessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/health"
            port: "http"
            scheme: HTTP
        readinessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/health"
            port: "http"
            scheme: HTTP
        env:
          []
