---
# Source: rasa-x/templates/duckling-deployment.yaml
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: my-rasa-duckling
  labels:
    helm.sh/chart: rasa-x-5.0.0
    app.kubernetes.io/name: rasa-x
    app.kubernetes.io/instance: my-rasa
    app.kubernetes.io/version: "1.4.0"
    app.kubernetes.io/managed-by: Helm
    
    app.kubernetes.io/component: duckling
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rasa-x
      app.kubernetes.io/instance: my-rasa
      app.kubernetes.io/component: duckling
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rasa-x
        app.kubernetes.io/instance: my-rasa
        app.kubernetes.io/component: duckling
    spec:
      hostNetwork: false
      dnsPolicy: ClusterFirst
      automountServiceAccountToken: false
      
      securityContext:
        fsGroup: 1000
      containers:
      - name: rasa-x
        image: "rasa/duckling:0.2.0.2"
        imagePullPolicy: Always
        env:
        
        ports:
        - name: "http"
          containerPort: 8000
          protocol: "TCP"
        livenessProbe:
          httpGet:
            path: "/"
            port: "http"
            scheme: HTTP
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: "/"
            port: "http"
            scheme: HTTP
          initialDelaySeconds: 10
