---
# Source: rasa-x/templates/event-service-deployment.yaml
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: my-rasa-event-service
  labels:
    helm.sh/chart: rasa-x-5.0.0
    app.kubernetes.io/name: rasa-x
    app.kubernetes.io/instance: my-rasa
    app.kubernetes.io/version: "1.4.0"
    app.kubernetes.io/managed-by: Helm
    
    app.kubernetes.io/component: event-service
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rasa-x
      app.kubernetes.io/instance: my-rasa
      app.kubernetes.io/component: event-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rasa-x
        app.kubernetes.io/instance: my-rasa
        app.kubernetes.io/component: event-service
    spec:
      hostNetwork: false
      dnsPolicy: ClusterFirst
      automountServiceAccountToken: false
      
      
      securityContext:
        fsGroup: 1000
      
      containers:
      - name: rasa-x
        image: "rasa/rasa-x:1.4.0"
        imagePullPolicy: Always
        args:
          - python
          - -m
          - rasax.community.services.event_service
        ports:
          - name: "http"
            containerPort: 5673
            protocol: "TCP"
        livenessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/health"
            port: "http"
            scheme: HTTP
        
        readinessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/health"
            port: "http"
            scheme: HTTP
        
        env:
        - name: "SELF_PORT"
          value: "5673"
        - name: "RABBITMQ_QUEUE"
          value: "rasa_production_events"
        - name: "RABBITMQ_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: "my-rasa-rabbit"
              key: "rabbitmq-password"
        
        - name: "REDIS_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: "my-rasa-redis"
              key: "redis-password"

        - name: "RASA_X_USER_ANALYTICS"
          value: "0"
        - name: "LOCAL_MODE" # This variable doesn't do anything anymore in Rasa X 0.28 and later
          value: "false"
        - name: "DB_USER"
          value: "postgres"
        - name: "DB_HOST"
          value: "my-rasa-postgresql"
        - name: "DB_PORT"
          value: "5432"
        - name: "DB_DATABASE"
          value: "rasa"
        - name: "DB_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: "my-rasa-postgresql"
              key: postgresql-password
        
        volumeMounts:
        - mountPath: "/app/endpoints.yml"
          subPath: "endpoints.yml"
          name: "rasa-configuration"
      volumes:
      - name: "rasa-configuration"
        configMap:
          name: "my-rasa-rasa-configuration-files"
          items:
            - key: "rasa-endpoints"
              path: "endpoints.yml"
