---
# Source: rasa-x/templates/rasa-services.yaml
apiVersion: "v1"
kind: "Service"
metadata:
  name: my-rasa-rasa-x-rasa-worker
  labels:
    helm.sh/chart: rasa-x-5.0.0
    app.kubernetes.io/name: rasa-x
    app.kubernetes.io/instance: my-rasa
    app.kubernetes.io/version: "1.4.0"
    app.kubernetes.io/managed-by: Helm
    
    app.kubernetes.io/component: rasa-worker
spec:
  ports:
  - port: 5005
    targetPort: 5005
    protocol: TCP
  selector:
    app.kubernetes.io/name: rasa-x
    app.kubernetes.io/instance: my-rasa
    app.kubernetes.io/component: rasa-worker

# this is needed to make it clear that these are two resources
