---
# Source: rasa-x/templates/rasa-x-volumeclaim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-rasa-rasa-x-claim
  namespace: default
  labels:
    helm.sh/chart: rasa-x-5.0.0
    app.kubernetes.io/name: rasa-x
    app.kubernetes.io/instance: my-rasa
    app.kubernetes.io/version: "1.4.0"
    app.kubernetes.io/managed-by: Helm
    
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
