---
# Source: rasa-x/charts/rabbitmq/templates/rolebinding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: my-rasa-rabbit-endpoint-reader
  namespace: "default"
  labels:
    app.kubernetes.io/name: rabbitmq
    helm.sh/chart: rabbitmq-8.32.2
    app.kubernetes.io/instance: my-rasa
    app.kubernetes.io/managed-by: Helm
subjects:
  - kind: ServiceAccount
    name: my-rasa-rabbit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: my-rasa-rabbit-endpoint-reader
