---
# Source: rasa-x/charts/redis/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-rasa-redis
  namespace: "default"
  labels:
    app.kubernetes.io/name: redis
    helm.sh/chart: redis-15.7.6
    app.kubernetes.io/instance: my-rasa
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  redis-password: "cmVkaXMtcGFzc3dvcmQ="
